#page title
page_title                                : Anybuffer

# App Info
ios_app_id                                : 1330815414                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Drag and Drop Clipboard for iOS
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ameba                                
your_link                                 : https://ameba.co                    
your_city                                 : Washington DC                                
email_address                             : info@ameba.co
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : amebalabs
github_username                           : amebalabs
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Save, Organize, Share
    description                           : Add items with drag and drop, organize them into shelves, share with other apps or use within Anybuffer.
    fontawesome_icon_name                 : boxes
    
  - title                                 : Multiple Windows
    description                           : iOS 13 multiple windows environment on iPad, which ideally blends with multi-shelf system in Anybuffer.
    fontawesome_icon_name                 : th-large

  - title                                 : Siri Shortcuts
    description                           : Robust support for iOS 13 Siri Shortcuts. Automate interactions with Anybuffer in Shortcuts app.
    fontawesome_icon_name                 : microphone

  - title                                 : Document Scanner
    description                           : Scan documents directly into Anybuffer using a built-in scanner view.
    fontawesome_icon_name                 : file-image

  - title                                 : Contextual Menus
    description                           : Long press on item or shelf to access quick actions through new iOS 13 Contextual Menus.
    fontawesome_icon_name                 : bars

  - title                                 : Dark Mode
    description                           : Native Dark Mode support, follow system appearance or override the default behavior in Anybuffer Settings.
    fontawesome_icon_name                 : moon



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : white                                  # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#3478f6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#3478f6"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
